source 'https://rubygems.org'
gem 'sinatra', :github => 'sinatra/sinatra'
gem 'sinatra-contrib' # for 'sinatra/reloader'
gem 'thin'
gem 'puma'
gem 'reel'
gem 'http'
gem 'webrick'
gem 'byebug'

gem 'haml'
gem 'dotenv'
gem 'jwt'
gem 'xero-ruby'
